#!/bin/bash
source ./scripts/load-config
export | sudo tee /api/environment >/dev/null
sudo chown root:judge0 /api/environment
sudo chmod 0640 /api/environment

for _ in $(seq 1 "$RESTART_MAX_TRIES"); do
    [[ -f tmp/pids/server.pid ]] && rm -f -- tmp/pids/server.pid

    rails db:create db:migrate db:seed
    rails s -b 0.0.0.0
    [[ $? -eq 0 ]] && break
    sleep 2s
done
